name: panther_auth_system
description: A simple command-line application.
version: 1.0.0

environment:
  sdk: '>=2.14.3 <3.0.0'

dev_dependencies:
  lints: ^1.0.0
dependencies: 
  mysql1: ^0.19.2
  shelf: ^1.2.0
  shelf_router: ^1.1.1
  args: ^2.3.0
  crypto: ^3.0.1
